### ISSUE TITLE
Event binding directly in onClick property

### ISSUE THREAD

**Issue by jrtilson** [Morsadi/Scale-Changer#2]
https://github.com/Morsadi/Scale-Changer/blob/d42cbd17ff3d4f52d1a23e117b9575ad6d7bca56/src/App.js#L182

While not incorrect, I'm about 90% sure that binding event handlers directly is a deprecated practice. What I do instead, is bind the events in the component constructor, then just reference the function in the onClick property, ie:

```
  constructor(props) {
    super(props)
    ...
    this.addChord = this.addChord.bind(this)
  }
```

Then in the JSX:

```
 <input className='addBtn' onClick={this.addChord} ... />
```

It's a bit cleaner and keeps all your bound events defined in a nice little list

**Comment by Morsadi** [comment]
Yes, in my latest project I used the arrow function which seemed to work
perfectly without even needing to bind it. Do you think that’s a good
practice? Like,

addChord =()=>{
//code
}

**Comment by jrtilson** [comment]
Wether or not you need to bind the function depends on what the function does, in this case the addChord function is accessing the components state, so it does need to be bound to the component (to access this.state). If your function doesn't use the component's props or state, you don't need to bind it.
